---
- name: tofi - compile from source
  block:
    - name: tofi - Install dependencies
      dnf:
        name:
          - freetype-devel
          - cairo-devel
          - pango-devel
          - wayland-devel
          - libxkbcommon-devel
          - harfbuzz
          - meson
          - scdoc
          - wayland-protocols-devel
    - name: tofi - clone repo

  when: compile_tofi
