---
- name: upgrade all packages
  dnf:
    name: "*"
    state: latest
  become: true
- name: Install dependencies fedora 22
  dnf:
    name:
      - python2-devel
      - qalsa-lib-devel
      - jack-audio-connection-kit-devel
      - libsamplerate-devel
      - liblrdf-devel
      - libsndfile-devel
      - ladspa-devel
      - glib2-devel
      - ladspa-calf-plugins
      - binutils-devel
      - libtool-ltdl
      - libtool
      - tk
      - libogg-devel
      - libvorbis-devel
      - speex-devel
      - fftw-devel
      - guile
      - libxkbfile-devel
      - xorg-x11-util-macros
      - cmake
      - libXrandr-devel
      - llvm-devel
      - boost-devel
      - openssl-devel
      - ncurses-devel
      - xcb-util-keysyms-devel
      - qt5-qtbase-gui
      - qt5-qttools-common
      - qt5-qtwebkit-devel
      - qt5-qtx11extras-devel
      - qt5-qttools-static
      - gmp-devel
      - mpfr-devel
      - libmpc-devel
    state: present
  become: true
- name: clone radium repo
  git:
    repo: 'https://github.com/kmatheussen/radium.git'
    dest: "{{ ansible_env.HOME }}/radium"
    version: 7.0.00
